CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL CHECK (role IN ('faculty', 'student', 'admin')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS events (
  id SERIAL PRIMARY KEY,
  faculty_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  details TEXT NOT NULL,
  outcome TEXT NOT NULL,
  event_date DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS attendance (
  id SERIAL PRIMARY KEY,
  student_usn VARCHAR(20) NOT NULL,
  faculty_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  date DATE NOT NULL,
  status VARCHAR(10) NOT NULL CHECK (status IN ('present', 'absent')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS marks (
  id SERIAL PRIMARY KEY,
  student_usn VARCHAR(20) NOT NULL,
  student_name VARCHAR(100) NOT NULL,
  course VARCHAR(100) NOT NULL,
  cie1 INTEGER DEFAULT 0,
  cie2 INTEGER DEFAULT 0,
  cie3 INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS aba (
  id SERIAL PRIMARY KEY,
  course VARCHAR(100) NOT NULL,
  topic VARCHAR(150) NOT NULL,
  details TEXT NOT NULL,
  last_date DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fees (
  id SERIAL PRIMARY KEY,
  student_name VARCHAR(100) NOT NULL,
  usn VARCHAR(20) NOT NULL,
  batch VARCHAR(20) NOT NULL,
  fees NUMERIC(10, 2) NOT NULL,
  paid BOOLEAN NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS staff (
  id SERIAL PRIMARY KEY,
  staff_name VARCHAR(100) NOT NULL,
  staff_id VARCHAR(50) NOT NULL,
  salary NUMERIC(10, 2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS circulars (
  id SERIAL PRIMARY KEY,
  description TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

